:gems:
  - yard
  - gem-ctags
  - gem-browse
  - bundler
  - terminal-notifier
  - pry
  - pry-doc
  - pry-theme
  - hirb
  - hirb-unicode
  - powder
  - seeing_is_believing
  - ruby-lint
  - rubocop
